//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace DCI.HRMS.Reports.PSN {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("FAR_Healty_Award")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class FAR_Healty_Award : global::System.Data.DataSet {
        
        private Healthy_AwardDataTable tableHealthy_Award;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public FAR_Healty_Award() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected FAR_Healty_Award(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Healthy_Award"] != null)) {
                    base.Tables.Add(new Healthy_AwardDataTable(ds.Tables["Healthy_Award"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Healthy_AwardDataTable Healthy_Award {
            get {
                return this.tableHealthy_Award;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            FAR_Healty_Award cln = ((FAR_Healty_Award)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Healthy_Award"] != null)) {
                    base.Tables.Add(new Healthy_AwardDataTable(ds.Tables["Healthy_Award"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableHealthy_Award = ((Healthy_AwardDataTable)(base.Tables["Healthy_Award"]));
            if ((initTable == true)) {
                if ((this.tableHealthy_Award != null)) {
                    this.tableHealthy_Award.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "FAR_Healty_Award";
            this.Prefix = "";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableHealthy_Award = new Healthy_AwardDataTable();
            base.Tables.Add(this.tableHealthy_Award);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeHealthy_Award() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            FAR_Healty_Award ds = new FAR_Healty_Award();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void Healthy_AwardRowChangeEventHandler(object sender, Healthy_AwardRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Healthy_AwardDataTable : global::System.Data.TypedTableBase<Healthy_AwardRow> {
            
            private global::System.Data.DataColumn columnCODE;
            
            private global::System.Data.DataColumn columnPREN;
            
            private global::System.Data.DataColumn columnNAME;
            
            private global::System.Data.DataColumn columnSURN;
            
            private global::System.Data.DataColumn columnTPREN;
            
            private global::System.Data.DataColumn columnTNAME;
            
            private global::System.Data.DataColumn columnTSURN;
            
            private global::System.Data.DataColumn columnSEX;
            
            private global::System.Data.DataColumn columnIDNO;
            
            private global::System.Data.DataColumn columnJOIN;
            
            private global::System.Data.DataColumn columnPOSI_CD;
            
            private global::System.Data.DataColumn columnPOSI_ENAME;
            
            private global::System.Data.DataColumn columnGRPL;
            
            private global::System.Data.DataColumn columnDV_CD;
            
            private global::System.Data.DataColumn columnDV_ENAME;
            
            private global::System.Data.DataColumn columnFULLNAME;
            
            private global::System.Data.DataColumn columnTFULLNAME;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardDataTable() {
                this.TableName = "Healthy_Award";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Healthy_AwardDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Healthy_AwardDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CODEColumn {
                get {
                    return this.columnCODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PRENColumn {
                get {
                    return this.columnPREN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NAMEColumn {
                get {
                    return this.columnNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SURNColumn {
                get {
                    return this.columnSURN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TPRENColumn {
                get {
                    return this.columnTPREN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TNAMEColumn {
                get {
                    return this.columnTNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TSURNColumn {
                get {
                    return this.columnTSURN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SEXColumn {
                get {
                    return this.columnSEX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IDNOColumn {
                get {
                    return this.columnIDNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JOINColumn {
                get {
                    return this.columnJOIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn POSI_CDColumn {
                get {
                    return this.columnPOSI_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn POSI_ENAMEColumn {
                get {
                    return this.columnPOSI_ENAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GRPLColumn {
                get {
                    return this.columnGRPL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DV_CDColumn {
                get {
                    return this.columnDV_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DV_ENAMEColumn {
                get {
                    return this.columnDV_ENAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FULLNAMEColumn {
                get {
                    return this.columnFULLNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TFULLNAMEColumn {
                get {
                    return this.columnTFULLNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardRow this[int index] {
                get {
                    return ((Healthy_AwardRow)(this.Rows[index]));
                }
            }
            
            public event Healthy_AwardRowChangeEventHandler Healthy_AwardRowChanging;
            
            public event Healthy_AwardRowChangeEventHandler Healthy_AwardRowChanged;
            
            public event Healthy_AwardRowChangeEventHandler Healthy_AwardRowDeleting;
            
            public event Healthy_AwardRowChangeEventHandler Healthy_AwardRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddHealthy_AwardRow(Healthy_AwardRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardRow AddHealthy_AwardRow(
                        string CODE, 
                        string PREN, 
                        string NAME, 
                        string SURN, 
                        string TPREN, 
                        string TNAME, 
                        string TSURN, 
                        string SEX, 
                        string IDNO, 
                        System.DateTime JOIN, 
                        string POSI_CD, 
                        string POSI_ENAME, 
                        string GRPL, 
                        string DV_CD, 
                        string DV_ENAME, 
                        string FULLNAME, 
                        string TFULLNAME) {
                Healthy_AwardRow rowHealthy_AwardRow = ((Healthy_AwardRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CODE,
                        PREN,
                        NAME,
                        SURN,
                        TPREN,
                        TNAME,
                        TSURN,
                        SEX,
                        IDNO,
                        JOIN,
                        POSI_CD,
                        POSI_ENAME,
                        GRPL,
                        DV_CD,
                        DV_ENAME,
                        FULLNAME,
                        TFULLNAME};
                rowHealthy_AwardRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowHealthy_AwardRow);
                return rowHealthy_AwardRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                Healthy_AwardDataTable cln = ((Healthy_AwardDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new Healthy_AwardDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCODE = base.Columns["CODE"];
                this.columnPREN = base.Columns["PREN"];
                this.columnNAME = base.Columns["NAME"];
                this.columnSURN = base.Columns["SURN"];
                this.columnTPREN = base.Columns["TPREN"];
                this.columnTNAME = base.Columns["TNAME"];
                this.columnTSURN = base.Columns["TSURN"];
                this.columnSEX = base.Columns["SEX"];
                this.columnIDNO = base.Columns["IDNO"];
                this.columnJOIN = base.Columns["JOIN"];
                this.columnPOSI_CD = base.Columns["POSI_CD"];
                this.columnPOSI_ENAME = base.Columns["POSI_ENAME"];
                this.columnGRPL = base.Columns["GRPL"];
                this.columnDV_CD = base.Columns["DV_CD"];
                this.columnDV_ENAME = base.Columns["DV_ENAME"];
                this.columnFULLNAME = base.Columns["FULLNAME"];
                this.columnTFULLNAME = base.Columns["TFULLNAME"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCODE = new global::System.Data.DataColumn("CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCODE);
                this.columnPREN = new global::System.Data.DataColumn("PREN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPREN);
                this.columnNAME = new global::System.Data.DataColumn("NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAME);
                this.columnSURN = new global::System.Data.DataColumn("SURN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSURN);
                this.columnTPREN = new global::System.Data.DataColumn("TPREN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTPREN);
                this.columnTNAME = new global::System.Data.DataColumn("TNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTNAME);
                this.columnTSURN = new global::System.Data.DataColumn("TSURN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTSURN);
                this.columnSEX = new global::System.Data.DataColumn("SEX", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSEX);
                this.columnIDNO = new global::System.Data.DataColumn("IDNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDNO);
                this.columnJOIN = new global::System.Data.DataColumn("JOIN", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJOIN);
                this.columnPOSI_CD = new global::System.Data.DataColumn("POSI_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOSI_CD);
                this.columnPOSI_ENAME = new global::System.Data.DataColumn("POSI_ENAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOSI_ENAME);
                this.columnGRPL = new global::System.Data.DataColumn("GRPL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGRPL);
                this.columnDV_CD = new global::System.Data.DataColumn("DV_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDV_CD);
                this.columnDV_ENAME = new global::System.Data.DataColumn("DV_ENAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDV_ENAME);
                this.columnFULLNAME = new global::System.Data.DataColumn("FULLNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFULLNAME);
                this.columnTFULLNAME = new global::System.Data.DataColumn("TFULLNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTFULLNAME);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardRow NewHealthy_AwardRow() {
                return ((Healthy_AwardRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new Healthy_AwardRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(Healthy_AwardRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Healthy_AwardRowChanged != null)) {
                    this.Healthy_AwardRowChanged(this, new Healthy_AwardRowChangeEvent(((Healthy_AwardRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Healthy_AwardRowChanging != null)) {
                    this.Healthy_AwardRowChanging(this, new Healthy_AwardRowChangeEvent(((Healthy_AwardRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Healthy_AwardRowDeleted != null)) {
                    this.Healthy_AwardRowDeleted(this, new Healthy_AwardRowChangeEvent(((Healthy_AwardRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Healthy_AwardRowDeleting != null)) {
                    this.Healthy_AwardRowDeleting(this, new Healthy_AwardRowChangeEvent(((Healthy_AwardRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveHealthy_AwardRow(Healthy_AwardRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                FAR_Healty_Award ds = new FAR_Healty_Award();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Healthy_AwardDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Healthy_AwardRow : global::System.Data.DataRow {
            
            private Healthy_AwardDataTable tableHealthy_Award;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Healthy_AwardRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableHealthy_Award = ((Healthy_AwardDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CODE {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CODE\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PREN {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.PRENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PREN\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.PRENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SURN {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.SURNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SURN\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.SURNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TPREN {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.TPRENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TPREN\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.TPRENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TNAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.TNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TNAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.TNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TSURN {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.TSURNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TSURN\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.TSURNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SEX {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.SEXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SEX\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.SEXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IDNO {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.IDNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IDNO\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.IDNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime JOIN {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableHealthy_Award.JOINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JOIN\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.JOINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string POSI_CD {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.POSI_CDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POSI_CD\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.POSI_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string POSI_ENAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.POSI_ENAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POSI_ENAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.POSI_ENAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GRPL {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.GRPLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GRPL\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.GRPLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DV_CD {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.DV_CDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DV_CD\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.DV_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DV_ENAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.DV_ENAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DV_ENAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.DV_ENAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FULLNAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.FULLNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FULLNAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.FULLNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TFULLNAME {
                get {
                    try {
                        return ((string)(this[this.tableHealthy_Award.TFULLNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TFULLNAME\' in table \'Healthy_Award\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHealthy_Award.TFULLNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCODENull() {
                return this.IsNull(this.tableHealthy_Award.CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCODENull() {
                this[this.tableHealthy_Award.CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPRENNull() {
                return this.IsNull(this.tableHealthy_Award.PRENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPRENNull() {
                this[this.tableHealthy_Award.PRENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMENull() {
                return this.IsNull(this.tableHealthy_Award.NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMENull() {
                this[this.tableHealthy_Award.NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSURNNull() {
                return this.IsNull(this.tableHealthy_Award.SURNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSURNNull() {
                this[this.tableHealthy_Award.SURNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTPRENNull() {
                return this.IsNull(this.tableHealthy_Award.TPRENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTPRENNull() {
                this[this.tableHealthy_Award.TPRENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTNAMENull() {
                return this.IsNull(this.tableHealthy_Award.TNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTNAMENull() {
                this[this.tableHealthy_Award.TNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTSURNNull() {
                return this.IsNull(this.tableHealthy_Award.TSURNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTSURNNull() {
                this[this.tableHealthy_Award.TSURNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSEXNull() {
                return this.IsNull(this.tableHealthy_Award.SEXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSEXNull() {
                this[this.tableHealthy_Award.SEXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIDNONull() {
                return this.IsNull(this.tableHealthy_Award.IDNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIDNONull() {
                this[this.tableHealthy_Award.IDNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJOINNull() {
                return this.IsNull(this.tableHealthy_Award.JOINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJOINNull() {
                this[this.tableHealthy_Award.JOINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPOSI_CDNull() {
                return this.IsNull(this.tableHealthy_Award.POSI_CDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPOSI_CDNull() {
                this[this.tableHealthy_Award.POSI_CDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPOSI_ENAMENull() {
                return this.IsNull(this.tableHealthy_Award.POSI_ENAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPOSI_ENAMENull() {
                this[this.tableHealthy_Award.POSI_ENAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGRPLNull() {
                return this.IsNull(this.tableHealthy_Award.GRPLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGRPLNull() {
                this[this.tableHealthy_Award.GRPLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDV_CDNull() {
                return this.IsNull(this.tableHealthy_Award.DV_CDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDV_CDNull() {
                this[this.tableHealthy_Award.DV_CDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDV_ENAMENull() {
                return this.IsNull(this.tableHealthy_Award.DV_ENAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDV_ENAMENull() {
                this[this.tableHealthy_Award.DV_ENAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFULLNAMENull() {
                return this.IsNull(this.tableHealthy_Award.FULLNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFULLNAMENull() {
                this[this.tableHealthy_Award.FULLNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTFULLNAMENull() {
                return this.IsNull(this.tableHealthy_Award.TFULLNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTFULLNAMENull() {
                this[this.tableHealthy_Award.TFULLNAMEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Healthy_AwardRowChangeEvent : global::System.EventArgs {
            
            private Healthy_AwardRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardRowChangeEvent(Healthy_AwardRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Healthy_AwardRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591